name: Build and push

on:
  pull_request_target:
    branches: [ "master" ]  # Don't know if this works
    types:
      - closed
  push:
    branches:
    - "master"
  workflow_dispatch:

env:
  MAIN_BRANCH: master
permissions:
  contents: write
  packages: write

jobs:
  build-api:
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v6
    # - name: Build app image
    #   run: docker build . --tag image
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    - name: Image ID
      id: image
      run: |
        IMAGE_ID=ghcr.io/eiffel-community/etos-api
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "$MAIN_BRANCH" ] && VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "image=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
    - name: Push app image
      run: |
        # docker tag image ${{ steps.image.outputs.image }}
        echo "Pushing image ${{ steps.image.outputs.image }}"
        # docker push ${{ steps.image.outputs.image }}
    outputs:
      apiImage: ${{ steps.image.outputs.image }}
  build-sse:
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v6
    # - name: Build app image
    #   run: docker build . -f deploy/etos-sse/Dockerfile --tag image
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    - name: Image ID
      id: image
      run: |
        IMAGE_ID=ghcr.io/eiffel-community/etos-sse
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "$MAIN_BRANCH" ] && VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "image=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
    - name: Push app image
      run: |
        # docker tag image ${{ steps.image.outputs.image }}
        echo "Pushing image ${{ steps.image.outputs.image }}"
        # docker push ${{ steps.image.outputs.image }}
    outputs:
      sseImage: ${{ steps.image.outputs.image }}
  build-logarea:
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v6
    # - name: Build app image
    #   run: docker build . -f deploy/etos-logarea/Dockerfile --tag image
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    - name: Image ID
      id: image
      run: |
        IMAGE_ID=ghcr.io/eiffel-community/etos-logarea
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "$MAIN_BRANCH" ] && VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "image=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
    - name: Push app image
      run: |
        # docker tag image ${{ steps.image.outputs.image }}
        echo "Pushing image ${{ steps.image.outputs.image }}"
        # docker push ${{ steps.image.outputs.image }}
    outputs:
      logareaImage: ${{ steps.image.outputs.image }}
  build-keys:
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v6
    # - name: Build app image
    #   run: docker build . -f deploy/etos-keys/Dockerfile --tag image
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    - name: Image ID
      id: image
      run: |
        IMAGE_ID=ghcr.io/eiffel-community/etos-keys
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "$MAIN_BRANCH" ] && VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "image=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
    - name: Push app image
      run: |
        # docker tag image ${{ steps.image.outputs.image }}
        echo "Pushing image ${{ steps.image.outputs.image }}"
        # docker push ${{ steps.image.outputs.image }}
    outputs:
      keysImage: ${{ steps.image.outputs.image }}
  build-iut:
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v6
    # - name: Build app image
    #   run: docker build . -f deploy/etos-iut/Dockerfile --tag image
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    - name: Image ID
      id: image
      run: |
        IMAGE_ID=ghcr.io/eiffel-community/etos-iut
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "$MAIN_BRANCH" ] && VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "image=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
    - name: Push app image
      run: |
        # docker tag image ${{ steps.image.outputs.image }}
        echo "Pushing image ${{ steps.image.outputs.image }}"
        # docker push ${{ steps.image.outputs.image }}
    outputs:
      iutImage: ${{ steps.image.outputs.image }}
  build-executionspace:
    # if: ${{ github.event_name == 'workflow_dispatch' || github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    # - uses: actions/checkout@v6
    # - name: Build app image                     
    #   run: docker build . -f deploy/etos-executionspace/Dockerfile --tag image
    # - name: Login to GitHub Container Registry
    #   uses: docker/login-action@v3
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.actor }}
    #     password: ${{ secrets.GITHUB_TOKEN }}
    - name: Image ID
      id: image
      run: |
        IMAGE_ID=ghcr.io/eiffel-community/etos-executionspace
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
        # Use Docker `latest` tag convention
        [ "$VERSION" == "$MAIN_BRANCH" ] && VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        echo VERSION=$VERSION
        echo "image=$IMAGE_ID:$VERSION" >> $GITHUB_OUTPUT
    - name: Push app image
      run: |
        # docker tag image ${{ steps.image.outputs.image }}
        echo "Pushing image ${{ steps.image.outputs.image }}"
        # docker push ${{ steps.image.outputs.image }}
    outputs:
      executionSpaceImage: ${{ steps.image.outputs.image }}
  run-update-etos-defaults:
    needs: [build-api, build-sse, build-logarea]
    uses: ./.github/workflows/update-etos.yaml
    secrets: inherit
    with:
      api-image: ${{ needs.build-api.outputs.apiImage }}
      sse-image: ${{ needs.build-sse.outputs.sseImage }}
      logarea-image: ${{ needs.build-logarea.outputs.logareaImage }}
