# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Echo event name
      run: echo "Event name is ${{ github.event_name }}"
  # run-tox:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under , so your job can access it
  #     - uses: actions/checkout@v2

  #     - name: Setup python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.13
  #     - name: Install Tox
  #       run: pip install tox
  #     - name: Upgrade setuptools
  #       run: pip install -U setuptools
  #     - name: Run Tox
  #       run: tox
  #       working-directory: ./python
  # run-gotest:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       # Since we have 1.21 in the go.mod file, but toolchain is go1.22.1
  #       go-version: [ '1.21', '1.22.1' ]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Setup Go ${{ matrix.go-version }}
  #       uses: actions/setup-go@v5
  #       with:
  #         go-version: ${{ matrix.go-version }}
  #     - name: Go test
  #       run: make test
  # run-hadolint:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under , so your job can access it
  #     - uses: actions/checkout@v2

  #     - name: Run hadolint for API
  #       uses: hadolint/hadolint-action@master
  #       with:
  #         dockerfile: Dockerfile
  #     - name: Run hadolint for SSE
  #       uses: hadolint/hadolint-action@master
  #       with:
  #         dockerfile: deploy/etos-sse/Dockerfile
  #     - name: Run hadolint for KeyService
  #       uses: hadolint/hadolint-action@master
  #       with:
  #         dockerfile: deploy/etos-keys/Dockerfile
  #     - name: Run hadolint for LogArea
  #       uses: hadolint/hadolint-action@master
  #       with:
  #         dockerfile: deploy/etos-logarea/Dockerfile

  # build-docker-images:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under , so your job can access it
  #     - uses: actions/checkout@v2

  #     - name: Build API image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./Dockerfile
  #     - name: Build SSE image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./deploy/etos-sse/Dockerfile
  #     - name: Build KeyService image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./deploy/etos-keys/Dockerfile
  #     - name: Build LogArea image
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: .
  #         file: ./deploy/etos-logarea/Dockerfile
